# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczka_1_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtyczka1DialogBase(object):
    def setupUi(self, wtyczka1DialogBase):
        wtyczka1DialogBase.setObjectName("wtyczka1DialogBase")
        wtyczka1DialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(wtyczka1DialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(wtyczka1DialogBase)
        self.button_box.accepted.connect(wtyczka1DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(wtyczka1DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wtyczka1DialogBase)

    def retranslateUi(self, wtyczka1DialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyczka1DialogBase.setWindowTitle(_translate("wtyczka1DialogBase", "projekt2"))
