# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczka_1_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtyczka1DialogBase(object):
    def setupUi(self, wtyczka1DialogBase):
        wtyczka1DialogBase.setObjectName("wtyczka1DialogBase")
        wtyczka1DialogBase.resize(564, 491)
        self.button_box = QtWidgets.QDialogButtonBox(wtyczka1DialogBase)
        self.button_box.setGeometry(QtCore.QRect(190, 420, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.mMapLayerComboBox = QgsMapLayerComboBox(wtyczka1DialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(70, 90, 281, 31))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.label = QtWidgets.QLabel(wtyczka1DialogBase)
        self.label.setGeometry(QtCore.QRect(70, 60, 161, 16))
        self.label.setObjectName("label")

        self.retranslateUi(wtyczka1DialogBase)
        self.button_box.accepted.connect(wtyczka1DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(wtyczka1DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wtyczka1DialogBase)

    def retranslateUi(self, wtyczka1DialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyczka1DialogBase.setWindowTitle(_translate("wtyczka1DialogBase", "projekt2"))
        self.label.setText(_translate("wtyczka1DialogBase", "Wybierz warstwę:"))
from qgsmaplayercombobox import QgsMapLayerComboBox
